### ISSUE TITLE
Potential issue in pytorch > dataloader.py > class CholecT50

### ISSUE THREAD

**Issue by yc443** [CAMMA-public/tripnet#1]
Hello!

In "https://github.com/CAMMA-public/tripnet/blob/main/pytorch/dataloader.py > class CholecT50 >(init function)>self.augmentations ":
there are two "contrast" keys in the dictionary. It seems to me that the first one will be overwritten, may I ask if they meant to have different key names or is there any reason about reassigning the value?

I have also checked https://github.com/CAMMA-public/cholect45/blob/main/dataloader_pth.py which has the same "self.augmentations" dictionary (2 "contrast" keys), so would really appreciate your help for clearing up my confusion. 

Many thanks in advance!

**Comment by nwoyecid** [comment]
Thank you for pointing this out.

Indeed the last `contrast`  is `rcontrast` which stands for random contrast. You can change the key in your code. I have edited this waiting for the next commit.

**Comment by yc443** [comment]
Great, thank you!
