### ISSUE TITLE
Potential issue in pytorch > run.py > default setting for --initial_learning_rates

### ISSUE THREAD

**Issue by yc443** [CAMMA-public/tripnet#2]
Hello,

I am wondering if the default setting in pytorch > run.py  for the ['-l'/' --initial_learning_rates'](https://github.com/CAMMA-public/tripnet/blob/e4bc921681be61d04bba136405df8cc4fabfb3d1/pytorch/run.py#L79) is meant to be 'default=[0.01, 0.01, 0.01]', instead of 'default=[0,0.01, 0.01, 0.01]'?

In the meantime, may I ask if the setting to obtain the performance in [Results Table](https://github.com/CAMMA-public/tripnet#results-table) is as default? I am struggling to get similar mAP results.

Many thanks in advance!

**Comment by nwoyecid** [comment]
The default values argparse are there to give users an idea of the format of the required values. 
The parameters for obtaining the model performance are contained in the published papers!
